MainCDR_MapScripts::
	.byte 0


CDR1::
	lock
	faceplayer
	msgbox CDR1_Text_0
	releaseall
	end


CDR2::
	lock
	faceplayer
	msgbox CDR2_Text_0
	releaseall
	end


CDR3::
	lock
	faceplayer
	msgbox CDR3_Text_0
	releaseall
	end


CDR4::
	lock
	faceplayer
	msgbox CDR4_Text_0
	releaseall
	end


CDR5::
	lock
	faceplayer
	msgbox CDR5_Text_0
	releaseall
	end


CDR6::
	lock
	faceplayer
	msgbox CDR6_Text_0
	releaseall
	end


CDR7::
	msgbox CDR7_Text_0
	msgbox CDR7_Text_1
	msgbox CDR7_Text_2
	releaseall
	end


CDR1_Text_0:
	.string "Le Centre de Recherches a été créé en\n"
	.string "1812 par un Professeur originaire de la\l"
	.string "région de Sinnoh. Il possède une\l"
	.string "surface de 3.5 hectares. Depuis sa\l"
	.string "création il héberge des espèces en\l"
	.string "voie de disparition et veille à leur\l"
	.string "qualité de vie.$"

CDR2_Text_0:
	.string "Dès 1939, des Professeurs de\n"
	.string "différentes régions s'y sont installés\l"
	.string "car il est très bien équipé et facilite\l"
	.string "énormément leurs recherches. Ils\l"
	.string "apportèrent des Pokémon rares de\l"
	.string "leurs régions respectives.$"

CDR3_Text_0:
	.string "Depuis 1998 a lieu un congrès dédié à la\n"
	.string "recherche scientifique concernant la\l"
	.string "préservation des Pokémon. Depuis 2004,\l"
	.string "des sociétés diverses commercialisant\l"
	.string "des produits dédiés au dresseurs tel\l"
	.string "que Sylph co., Devon SARL et Vitalis\l"
	.string "Navitas, dit V.N S.A.R.L. participent à\l"
	.string "ces congrès, dans le but de présenter\l"
	.string "leurs créations.$"

CDR4_Text_0:
	.string "En 2013, le Centre de Recherches a été\n"
	.string "reconnu comme patrimoine scientifique\l"
	.string "par l'UNPEVD (Union Nationale de\l"
	.string "Préservation des Espèces en Voie de\l"
	.string "Disparition.$"

CDR5_Text_0:
	.string "En 2014, le Centre de Recherches a fait\n"
	.string "l'objet d'un attentat terroriste, qui\l"
	.string "aura détruit plusieurs biotopes et\l"
	.string "écosystème, donc conduit des espèces\l"
	.string "en voie de disparition à leur\l"
	.string "extinction totale. Depuis cela, le\l"
	.string "Centre de Recherches et devenu\l"
	.string "interdit au public et très protégé.$"

CDR6_Text_0:
	.string "En 2017, il a été décidé par les 7\n"
	.string "membres du Conseil International de la\l"
	.string "recherche que 3 personnes parmis les\l"
	.string "plus brillantes des différentes\l"
	.string "académies, pas plus pour ne pas\l"
	.string "influencer les écosystèmes seront\l"
	.string "tirées au sort dans le but de recevoir\l"
	.string "un Pokémon rare. Tout cela pour\l"
	.string "permettre à ces espèces d'évoluer plus\l"
	.string "vite. Ces heureuses personnes seront\l"
	.string "nommées 'Boursiers', en effet, le\l"
	.string "Centre de Recherches couvrira\l"
	.string "l'intégralité des frais d'inscriptions\l"
	.string "au tournoi des arènes et, dans une\l"
	.string "moindre mesure au grand tournoi\l"
	.string "d'Olnyris tout en leur offrant un\l"
	.string "Pokédex.$"

CDR7_Text_0:
	.string "Noms des dresseurs de la première\n"
	.string "promotion des dresseurs du CDR:$"

CDR7_Text_1:
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}2013 : Apostrate, Appolonia, Zûhr$"

CDR7_Text_2:
	.string "Aujourd'hui, ces trois dresseurs sont\n"
	.string "les plus puissants de la région.$"
