#ifndef GUARD_CONSTANTS_MUGSHOTS_H
#define GUARD_CONSTANTS_MUGSHOTS_H

#define MUGSHOT_MIDORI 0
#define MUGSHOT_MIDORI_HAPPY 1
#define MUGSHOT_LISA 2
#define MUGSHOT_SCHWARTZ 3
#define MUGSHOT_LISA_CRY1 4
#define MUGSHOT_LISA_CRY2 5
#define MUGSHOT_LISA_CRY3 6
#define MUGSHOT_LISA_HAPPY 7
#define MUGSHOT_LISA_SAD 8
#define MUGSHOT_LISA_AWK 9
#define MUGSHOT_LISA_ANGRY 10

#endif