gText_Birch_Welcome::
	.string "......................                                                              \l"
	.string "Présentatrice : Chers téléspectateurs,\n"
	.string "aujourd'hui,\p"
	.string "Olnyris TV vous présente le centre de\n"
	.string "recherches. Un endroit inaccessible\p"
	.string "au public. Nous avons le privilège\n"
	.string "d'interviewer le grand, le célèbre\p"
	.string "et l'ingénieux Prof.Shwartz.\n"
	.string "Bien, assez parlé, nous lui laissons\p"
	.string "la parole.\l"
	.string "...............................                                                      \l"
	.string "Guten tag, je suis le Prof. Shwartz\n"
	.string "Demain, trois jeunes adultes auront le\p"
	.string "privilège de venir ici, ils ont été\n"
	.string "tirés au sort parmis une bonne\p"
	.string "centaine de personnes. Comme\n"
	.string "à chaque année.\p"
	.string "Ici vivent sans manquer de rien\l"
	.string "des espèces rares et protégées dans\l"
	.string "les meilleures conditions possibles.\n"
	.string "Trève de blabla, je vous en montre un\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Montre-toi !$"

gText_Birch_MainSpeech::
	.string "C'est un Krarmor, heim, pardon\n"
	.string "ein Corvallius en français.\p"
	.string "N'est-il pas magnifique ?\n"
	.string "Cet endroit est très surveillé\p"
	.string "seuls les scientifiques les plus\n"
	.string "brillants peuvent y accéder. Les\p"
	.string "personnes que le hasard a choisi sont\n"
	.string "les suivantes : le premier se nomme\p"
	.string "Midori, originaire de Kanto. \n"
	.string "La deuxième quant à elle se nomme\p"
	.string "Lisa, elle vient d'Unys.$"

gText_Birch_AndYouAre::
	.string "Enfin, le troisième, le seul\n"
	.string "à ne pas être un étudiant\p"
	.string "international.$"

gText_Birch_BoyOrGirl::
	.string "C'est un.. une?\p"
	.string "(C'est une fille ou un garçon?)$"

gText_Birch_WhatsYourName::
	.string "... erm, il se nomme...\p"
	.string "C'est quoi son nom déjà?$"

gText_Birch_SoItsPlayer::
	.string "{PLAYER}{KUN} c'est cela?$"

gText_Birch_YourePlayer::
	.string "Le troisième est {PLAYER}{KUN}\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Bien.\p"
	.string "Leur aventure est sur le\n"
	.string "point de commencer. Demain\p"
	.string "Ils obtiendront un Pokédex,\n"
	.string "un Pokémon et quelques objets\p"
	.string "qui les aideront pour leur aventure\n"
	.string "Peut être qu'ils gagneront la ligue\p"
	.string "qui sait. Soit, merci pour votre attention.\l"
	.string "FIN DU REPORTAGE\p"
	.string "OLNYRIS TV$"
